### ISSUE TITLE
Use remotes other than 'origin'

### ISSUE THREAD

**Issue by stoewer** [zalando-stups/python-scm-source#10]
When working with a fork of the original repository I usually have a setup with multiple remotes. In such setups it is very common to refer to the original repository as `upstream` and use `origin` to point to my own fork.

Such a setup `scm-source` should pick the remote `upstream` and not `origin`.

Solutions:
1. Check if a remote called `upstream` exists. If yes, chose this remote to get the URL.
2. Add a parameter `--remote` that lets the user chose which remote is used to get the URL.

**Comment by hjacobs** [comment]
I would prefer adding an option instead of implicitly assuming some convention.
