### ISSUE TITLE
Return an error code when source is locally modified

### ISSUE THREAD

**Issue by reactormonk** [zalando-stups/python-scm-source#9]
I'd like to check & abort deployment if scm-source detects that the source has been locally modified.

**Comment by amrhassan** [comment]
I just came in here to request this as well.

**Comment by hjacobs** [comment]
Sounds reasonable, feel free to do a PR (should be easy enough) :smile:

**Comment by hjacobs** [comment]
Released in https://github.com/zalando-stups/python-scm-source/releases/tag/1.0.10
